import Enum_Collection;




/*This class is just a collection Of tag that is not general tag.
Which means that these tags is supposed to be specific to certain museum and exhibitio.
PENDING: Please make JSON tag generator to generate everything premade within this program.*/
class CollectionPremadeTag{





    /*==================================================*/
    public function new(){}
    /*==================================================*/





    /*==================================================*/
    public static function PremadeTagStructVoid(_collectionGlobalObject:CollectionGlobal){

        new Tag_Object(_collectionGlobalObject, NEUTRAL  , ADJ                                           , false, "Aged")                        ._TagAgnostic_Object.SetAdjective_TagAgnostic_Object("Aged");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , ADJ                                           , false, "Bronze")                      ._TagAgnostic_Object.SetAdjective_TagAgnostic_Object("Bronze");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , ADJ                                           , false, "Copper")                      ._TagAgnostic_Object.SetAdjective_TagAgnostic_Object("Copper");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , ADJ                                           , false, "Masked")                      ._TagAgnostic_Object.SetAdjective_TagAgnostic_Object("Masked");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , ADJ                                           , false, "Metal")                       ._TagAgnostic_Object.SetAdjective_TagAgnostic_Object("Metal");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , ADJ                                           , false, "Oval")                        ._TagAgnostic_Object.SetAdjective_TagAgnostic_Object("Oval");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , ADJ                                           , false, "Slender")                     ._TagAgnostic_Object.SetAdjective_TagAgnostic_Object("Slender");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_ALIVE_ABSTRACT                           , false, "Animal")                      ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Animal")                      ._TagAgnostic_Object.SetNounPos_TagAgnostic_Object("Animal's")                         ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Animals")                    ._TagAgnostic_Object.SetNounSPos_TagAgnostic_Object("Animals'");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_ALIVE_ABSTRACT                           , false, "Archaeologist")               ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Archaeologist")               ._TagAgnostic_Object.SetNounPos_TagAgnostic_Object("Archaeologist's")                  ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Archaeologists")             ._TagAgnostic_Object.SetNounSPos_TagAgnostic_Object("Archaeologists'");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_ALIVE_ABSTRACT                           , false, "Female")                      ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Female")                      ._TagAgnostic_Object.SetNounPos_TagAgnostic_Object("Female's")                         ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Females")                    ._TagAgnostic_Object.SetNounSPos_TagAgnostic_Object("Females'");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_ALIVE_ABSTRACT                           , false, "Goldsmith")                   ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Goldsmith")                   ._TagAgnostic_Object.SetNounPos_TagAgnostic_Object("Goldsmith's")                      ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Goldsmiths")                 ._TagAgnostic_Object.SetNounSPos_TagAgnostic_Object("Goldsmiths'");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_ALIVE_ABSTRACT                           , false, "Infant")                      ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Infant")                      ._TagAgnostic_Object.SetNounPos_TagAgnostic_Object("Infant's")                         ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Infants")                    ._TagAgnostic_Object.SetNounSPos_TagAgnostic_Object("Infants'");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_ALIVE_ABSTRACT                           , false, "Lion")                        ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Lion")                        ._TagAgnostic_Object.SetNounPos_TagAgnostic_Object("Lion's")                           ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Lions")                      ._TagAgnostic_Object.SetNounSPos_TagAgnostic_Object("Lions'");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_ALIVE_ABSTRACT                           , false, "Man")                         ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Man")                         ._TagAgnostic_Object.SetNounPos_TagAgnostic_Object("Man's")                            ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Young men")                  ._TagAgnostic_Object.SetNounSPos_TagAgnostic_Object("Young men's");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_ALIVE_ABSTRACT                           , false, "Mauri")                       ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Mauri")                       ._TagAgnostic_Object.SetNounPos_TagAgnostic_Object("Mauri's")                          ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Mauris")                     ._TagAgnostic_Object.SetNounSPos_TagAgnostic_Object("Mauris'");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_ALIVE_ABSTRACT                           , false, "Peloponnese")                 ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Peloponnese")                 ._TagAgnostic_Object.SetNounPos_TagAgnostic_Object("Peloponnese's")                    ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Peloponneses")               ._TagAgnostic_Object.SetNounSPos_TagAgnostic_Object("Peloponneses'");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_ALIVE_ABSTRACT                           , false, "Warrior")                     ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Warrior")                     ._TagAgnostic_Object.SetNounPos_TagAgnostic_Object("Warrior's")                        ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Warriors")                   ._TagAgnostic_Object.SetNounSPos_TagAgnostic_Object("Warriors'");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_ALIVE_ABSTRACT                           , false, "Wolf")                        ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Wolf")                        ._TagAgnostic_Object.SetNounPos_TagAgnostic_Object("Wolf's")                           ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Wolfs")                      ._TagAgnostic_Object.SetNounSPos_TagAgnostic_Object("Wolfs'");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_ALIVE_ABSTRACT                           , false, "Woman")                       ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Woman")                       ._TagAgnostic_Object.SetNounPos_TagAgnostic_Object("Woman's")                          ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Women")                      ._TagAgnostic_Object.SetNounSPos_TagAgnostic_Object("Women's");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_ALIVE_CONCRETE                           , false, "Ferdinand De Rothschild")     ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Ferdinand De Rothschild")     ._TagAgnostic_Object.SetNounPos_TagAgnostic_Object("Ferdinand De Rothschild's");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_ALIVE_CONCRETE                           , false, "James")                       ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("James")                       ._TagAgnostic_Object.SetNounPos_TagAgnostic_Object("James'");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_ALIVE_CONCRETE                           , false, "John Duke Of Berry")          ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("John Duke Of Berry")          ._TagAgnostic_Object.SetNounPos_TagAgnostic_Object("John Duke Of Berry's");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_ALIVE_CONCRETE                           , false, "The Sutton Hoo")              ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("The Sutton Hoo")              ._TagAgnostic_Object.SetNounPos_TagAgnostic_Object("The Sutton Hoo's");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_HOLD_CONCRETE                  , false, "Bowl")                        ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Bowl")                        ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Bowls");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_HOLD_CONCRETE                  , false, "Chain")                       ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Chain")                       ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Chains");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_HOLD_CONCRETE                  , false, "Cista")                       ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Cista")                       ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Cistas");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_HOLD_CONCRETE                  , false, "Club")                        ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Club")                        ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Clubs");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_HOLD_CONCRETE                  , false, "Cosmetic")                    ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Cosmetic")                    ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Cosmetics");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_HOLD_CONCRETE                  , false, "Figurine")                    ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Figurine")                    ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Figurines");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_HOLD_CONCRETE                  , false, "Garnet")                      ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Garnet")                      ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Garnets");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_HOLD_CONCRETE                  , false, "Gold")                        ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Gold")                        ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Golds");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_HOLD_CONCRETE                  , false, "Ingot")                       ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Ingot")                       ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Ingots");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_HOLD_CONCRETE                  , false, "Item")                        ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Item")                        ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Items");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_HOLD_CONCRETE                  , false, "Jade")                        ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Jade")                        ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Jades");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_HOLD_CONCRETE                  , false, "Pearl")                       ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Pearl")                       ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Pearls");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_HOLD_CONCRETE                  , false, "Reliquary")                   ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Reliquary")                   ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Reliquaries");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_HOLD_CONCRETE                  , false, "Rose")                        ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Rose")                        ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Rosed");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_HOLD_CONCRETE                  , false, "Sapphire")                    ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Sapphire")                    ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Sapphires");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_HOLD_CONCRETE                  , false, "Spear")                       ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Spear")                       ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Spears");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_HOLD_CONCRETE                  , false, "Spear")                       ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Spear")                       ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Spears");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_HOLD_CONCRETE                  , false, "Statue")                      ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Statue")                      ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Statues");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_HOLD_CONCRETE                  , false, "Stone")                       ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Stone")                       ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Stones");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_HOLD_CONCRETE                  , false, "The Holy Thorn Reliquary")    ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("The Holy Thorn Reliquary")    ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("The Holy Thorn Reliquaries");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_HOLD_CONCRETE                  , false, "The Lyte Jewel")              ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("The Lyte Jewel")              ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("The Lyte Jewels");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_HOLD_CONCRETE                  , false, "Weapon")                      ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Weapon")                      ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Weapons");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_HOLD_CONCRETE                  , false, "Wood")                        ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Wood")                        ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Woods");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER        , false, "Boğazköy")                    ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Boğazköy");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER        , false, "Caenby")                      ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Caenby");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER        , false, "Cannatello")                  ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Cannatello");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER        , false, "Cape Gelidonya")              ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Cape Gelidonya");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER        , false, "Crete")                       ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Crete");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER        , false, "Cypriot")                     ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Cypriot");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER        , false, "Cyprus")                      ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Cyprus");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER        , false, "Cyprus")                      ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Cyprus");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER        , false, "Egypt")                       ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Egypt");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER        , false, "England")                     ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("England");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER        , false, "Hattusa")                     ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Hattusa");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER        , false, "Hittite")                     ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Hittite");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER        , false, "Lincolnshire")                ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Lincolnshire");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER        , false, "Louvre")                      ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Louvre");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER        , false, "Mediterranean")               ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Mediterranean");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER        , false, "Paris")                       ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Paris");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER        , false, "Qantir-Piramesse")            ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Qantir-Piramesse");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER        , false, "Sicily")                      ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Sicily");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER        , false, "Staffordshire")               ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Staffordshire");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER        , false, "Sweden")                      ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Sweden");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER        , false, "Turkey")                      ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Turkey");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER        , false, "Uluburun")                    ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Uluburun");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER        , false, "Valsgärde")                   ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Valsgärde");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER        , false, "Vendel")                      ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Vendel");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER        , false, "Waddesdon Bequest")           ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Waddesdon Bequest");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_OWNER           , false, "Burial")                      ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Burial")                      ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Burials");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_OWNER           , false, "Cradleboard")                 ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Cradleboard")                 ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Cradleboards");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_OWNER           , false, "Ship")                        ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Ship")                        ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Ships");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_OWNER           , false, "Table")                       ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Table")                       ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Tables");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_PLACE_CONCRETE_OWNER           , false, "Vessel")                      ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Vessel")                      ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Vessels");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_WEAR_ABSTRACT                  , false, "Valois")                      ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Valois");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_WEAR_CONCRETE                  , false, "Belt")                        ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Belt")                        ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Belts");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_WEAR_CONCRETE                  , false, "Crest")                       ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Crest")                       ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Crests");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_WEAR_CONCRETE                  , false, "Crown Of Thorn")              ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Crown Of Thorn")              ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Crown Of Thorns");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_WEAR_CONCRETE                  , false, "Helmet")                      ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Helmet")                      ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Helmets");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_WEAR_CONCRETE                  , false, "Jewel")                       ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Jewel")                       ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Jewels");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_WEAR_CONCRETE                  , false, "Mask")                        ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Mask")                        ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Mask");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_WEAR_CONCRETE                  , false, "Oxhide")                      ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Oxhide")                      ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Oxhides");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , NOUN_INANIMATE_WEAR_CONCRETE                  , false, "Pendant")                     ._TagAgnostic_Object.SetNoun_TagAgnostic_Object("Crown Of Thorn")              ._TagAgnostic_Object.SetNounS_TagAgnostic_Object("Crown Of Thorns");
        new Tag_Object(_collectionGlobalObject, NEUTRAL  , VERB_INTRANSITIVE                             , false, "Crouch")                      ._TagAgnostic_Object.SetVerb1_TagAgnostic_Object("Crouch")                     ._TagAgnostic_Object.SetVerb2_TagAgnostic_Object("Crouched")                           ._TagAgnostic_Object.SetVerb3_TagAgnostic_Object("Crouched")                   ._TagAgnostic_Object.SetVerbIng_TagAgnostic_Object("Crouching")                ._TagAgnostic_Object.SetVerbS_TagAgnostic_Object("Crouchs");
        new Tag_Object(_collectionGlobalObject, POSITIVE , ADJ                                           , false, "Extravagant")                 ._TagAgnostic_Object.SetAdjective_TagAgnostic_Object("Extravagant");
        new Tag_Object(_collectionGlobalObject, POSITIVE , ADV                                           , false, "Extravagantly")               ._TagAgnostic_Object.SetAdverb_TagAgnostic_Object("Extravagantly");

    }
    /*==================================================*/





}
