import CollectionEnum;
class CollectionTagGeneral{
    public function new(){}
    public static function TagGeneralStructVoid(_collectionGlobalObject:CollectionGlobal){
        TagGeneralStructAdjVoid(_collectionGlobalObject);
        TagGeneralStructAdvVoid(_collectionGlobalObject);
        TagGeneralStructNounAliveAbstractVoid(_collectionGlobalObject);
        TagGeneralStructNounAliveConcreteVoid(_collectionGlobalObject);
        TagGeneralStructNounInanimateHoldAbstractVoid(_collectionGlobalObject);
        TagGeneralStructNounInanimateHoldConcreteVoid(_collectionGlobalObject);
        TagGeneralStructNounInanimatePlaceAbstractVoid(_collectionGlobalObject);
        TagGeneralStructNounInanimatePlaceConcreteNoOwnerVoid(_collectionGlobalObject);
        TagGeneralStructNounInanimatePlaceConcreteOwnerVoid(_collectionGlobalObject);
        TagGeneralStructNounInanimateTitleAbstractVoid(_collectionGlobalObject);
        TagGeneralStructNounInanimateWearAbstractVoid(_collectionGlobalObject);
        TagGeneralStructNounInanimateWearConcreteVoid(_collectionGlobalObject);
        TagGeneralStructVerbVoidIntransitiveVoid(_collectionGlobalObject);
        TagGeneralStructVerbVoidTransitiveVoid(_collectionGlobalObject);
    }
    public static function TagGeneralStructAdjVoid(_collectionGlobalObject:CollectionGlobal){
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:ADJ,
                    tagString:"awful"
                },
                tagFeelEnum:NEGATIVE,
                tagTypeEnum:ADJ,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:ADJ,
                    tagString:"bad"
                },
                tagFeelEnum:NEGATIVE,
                tagTypeEnum:ADJ,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:ADJ,
                    tagString:"excellent"
                },
                tagFeelEnum:POSITIVE,
                tagTypeEnum:ADJ,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:ADJ,
                    tagString:"good"
                },
                tagFeelEnum:POSITIVE,
                tagTypeEnum:ADJ,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:ADJ,
                    tagString:"soft"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:ADJ,
            }
        );
    }
    public static function TagGeneralStructAdvVoid(_collectionGlobalObject:CollectionGlobal){
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:ADV,
                    tagString:"desperately"
                },
                tagFeelEnum:NEGATIVE,
                tagTypeEnum:ADV,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:ADV,
                    tagString:"slowly"
                },
                tagFeelEnum:NEGATIVE,
                tagTypeEnum:ADV,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:ADV,
                    tagString:"perfectly"
                },
                tagFeelEnum:POSITIVE,
                tagTypeEnum:ADV,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:ADV,
                    tagString:"quickly"
                },
                tagFeelEnum:POSITIVE,
                tagTypeEnum:ADV,
            }
        );
    }
    public static function TagGeneralStructNounAliveAbstractVoid(_collectionGlobalObject:CollectionGlobal){
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"assasin"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_POS,
                    tagString:"assasin's"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:NOUN_S,
                    tagString:"assasins"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:NOUN_S_POS,
                    tagString:"assasins'"
                },
                tagFeelEnum:NEGATIVE,
                tagTypeEnum:NOUN_ALIVE_ABSTRACT,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"boy"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_POS,
                    tagString:"boy's"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:NOUN_S,
                    tagString:"boys"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:NOUN_S_POS,
                    tagString:"boys'"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_ALIVE_ABSTRACT,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"dragon"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_POS,
                    tagString:"dragon's"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:NOUN_S,
                    tagString:"dragons"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:NOUN_S_POS,
                    tagString:"dragons'"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_ALIVE_ABSTRACT,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"iraqi"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_POS,
                    tagString:"iraqi's"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:NOUN_S,
                    tagString:"iraqis"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:NOUN_S_POS,
                    tagString:"iraqis'"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_ALIVE_ABSTRACT,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"italian"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_POS,
                    tagString:"italian's"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:NOUN_S,
                    tagString:"italian"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:NOUN_S_POS,
                    tagString:"italian'"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_ALIVE_ABSTRACT,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"painter"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_POS,
                    tagString:"painter's"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:NOUN_S,
                    tagString:"painters"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:NOUN_S_POS,
                    tagString:"painters'"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_ALIVE_ABSTRACT,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"romanian"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_POS,
                    tagString:"romanian's"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:NOUN_S,
                    tagString:"romanians"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:NOUN_S_POS,
                    tagString:"romanians'"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_ALIVE_ABSTRACT,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"russian"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_POS,
                    tagString:"russian's"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:NOUN_S,
                    tagString:"russians"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:NOUN_S_POS,
                    tagString:"russians'"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_ALIVE_ABSTRACT,
            }
        );
    }
    public static function TagGeneralStructNounAliveConcreteVoid(_collectionGlobalObject:CollectionGlobal){
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"Andy"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_POS,
                    tagString:"Andy's"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_ALIVE_CONCRETE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"Bodhisattva"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_POS,
                    tagString:"Bodhisattva's"
                },
                tagFeelEnum:POSITIVE,
                tagTypeEnum:NOUN_ALIVE_CONCRETE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"Buddha"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_POS,
                    tagString:"Buddha's"
                },
                tagFeelEnum:POSITIVE,
                tagTypeEnum:NOUN_ALIVE_CONCRETE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"Dimitri"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_POS,
                    tagString:"Dimitri's"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_ALIVE_CONCRETE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"Julius Caesar"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_POS,
                    tagString:"Julius Caesar's"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_ALIVE_CONCRETE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"Maria"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_POS,
                    tagString:"Maria's"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_ALIVE_CONCRETE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"Medusa"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_POS,
                    tagString:"Medusa's"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_ALIVE_CONCRETE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"Mikael"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_POS,
                    tagString:"Mikael's"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_ALIVE_CONCRETE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"Napoleon"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_POS,
                    tagString:"Napoleon's"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_ALIVE_CONCRETE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"Ramses"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_POS,
                    tagString:"Ramses'"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_ALIVE_CONCRETE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"Sphinx"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_POS,
                    tagString:"Sphinx's"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_ALIVE_CONCRETE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"Washington"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_POS,
                    tagString:"Washington's"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_ALIVE_CONCRETE,
            }
        );
    }
    public static function TagGeneralStructNounInanimateHoldAbstractVoid(_collectionGlobalObject:CollectionGlobal){
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"grudge"
                },
                tagFeelEnum:NEGATIVE,
                tagTypeEnum:NOUN_INANIMATE_HOLD_ABSTRACT,
            }
        );
    }
    public static function TagGeneralStructNounInanimateHoldConcreteVoid(_collectionGlobalObject:CollectionGlobal){
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"bat"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_S,
                    tagString:"bats"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_INANIMATE_HOLD_CONCRETE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"gun"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_S,
                    tagString:"guns"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_INANIMATE_HOLD_CONCRETE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"hand"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_S,
                    tagString:"hands"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_INANIMATE_HOLD_CONCRETE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"pencil"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_S,
                    tagString:"pencils"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_INANIMATE_HOLD_CONCRETE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"sword"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_S,
                    tagString:"swords"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_INANIMATE_HOLD_CONCRETE,
            }
        );
    }
    public static function TagGeneralStructNounInanimatePlaceAbstractVoid(_collectionGlobalObject:CollectionGlobal){
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"mind"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_INANIMATE_PLACE_ABSTRACT,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"peace"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_INANIMATE_PLACE_ABSTRACT,
            }
        );
    }
    public static function TagGeneralStructNounInanimatePlaceConcreteNoOwnerVoid(_collectionGlobalObject:CollectionGlobal){
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"India"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"Italia"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"Netherlands"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"Russia"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER,
            }
        );
    }
    public static function TagGeneralStructNounInanimatePlaceConcreteOwnerVoid(_collectionGlobalObject:CollectionGlobal){
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"country"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_INANIMATE_PLACE_CONCRETE_OWNER,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"harbor"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_INANIMATE_PLACE_CONCRETE_OWNER,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"house"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_INANIMATE_PLACE_CONCRETE_OWNER,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"school"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_INANIMATE_PLACE_CONCRETE_OWNER,
            }
        );
    }
    public static function TagGeneralStructNounInanimateTitleAbstractVoid(_collectionGlobalObject:CollectionGlobal){
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"commendation"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_S,
                    tagString:"commendations"
                },
                tagFeelEnum:POSITIVE,
                tagTypeEnum:NOUN_INANIMATE_TITLE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"job"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_S,
                    tagString:"jobs"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:NOUN_INANIMATE_TITLE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"praise"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:NOUN_S,
                    tagString:"praises"
                },
                tagFeelEnum:POSITIVE,
                tagTypeEnum:NOUN_INANIMATE_TITLE,
            }
        );
    }
    public static function TagGeneralStructNounInanimateWearAbstractVoid(_collectionGlobalObject:CollectionGlobal){
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"pride"
                },
                tagFeelEnum:POSITIVE,
                tagTypeEnum:NOUN_INANIMATE_WEAR_ABSTRACT,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"shame"
                },
                tagFeelEnum:NEGATIVE,
                tagTypeEnum:NOUN_INANIMATE_WEAR_ABSTRACT,
            }
        );
    }
    public static function TagGeneralStructNounInanimateWearConcreteVoid(_collectionGlobalObject:CollectionGlobal){
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"shirt"
                },
                tagFeelEnum:POSITIVE,
                tagTypeEnum:NOUN_INANIMATE_WEAR_CONCRETE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:NOUN,
                    tagString:"crown"
                },
                tagFeelEnum:NEGATIVE,
                tagTypeEnum:NOUN_INANIMATE_WEAR_CONCRETE,
            }
        );
    }
    public static function TagGeneralStructVerbVoidIntransitiveVoid(_collectionGlobalObject:CollectionGlobal){
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:VERB_1,
                    tagString:"die"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:VERB_2,
                    tagString:"died"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:VERB_3,
                    tagString:"died"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:VERB_ING,
                    tagString:"dying"
                },
                tagEntry5Struct:{
                    tagTypeSubEnum:VERB_S,
                    tagString:"dies"
                },
                tagFeelEnum:NEGATIVE,
                tagTypeEnum:VERB_INTRANSITIVE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:VERB_1,
                    tagString:"disintegrate"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:VERB_2,
                    tagString:"disintegrated"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:VERB_3,
                    tagString:"disintegrated"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:VERB_ING,
                    tagString:"disintegrating"
                },
                tagEntry5Struct:{
                    tagTypeSubEnum:VERB_S,
                    tagString:"disintegrates"
                },
                tagFeelEnum:NEGATIVE,
                tagTypeEnum:VERB_INTRANSITIVE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:VERB_1,
                    tagString:"jump"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:VERB_2,
                    tagString:"jumpe'"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:VERB_3,
                    tagString:"jumped"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:VERB_ING,
                    tagString:"jumping"
                },
                tagEntry5Struct:{
                    tagTypeSubEnum:VERB_S,
                    tagString:"jumps"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:VERB_INTRANSITIVE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:VERB_1,
                    tagString:"run"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:VERB_2,
                    tagString:"ran"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:VERB_3,
                    tagString:"ran"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:VERB_ING,
                    tagString:"running"
                },
                tagEntry5Struct:{
                    tagTypeSubEnum:VERB_S,
                    tagString:"runs"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:VERB_INTRANSITIVE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:VERB_1,
                    tagString:"sing"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:VERB_2,
                    tagString:"sang"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:VERB_3,
                    tagString:"sung"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:VERB_ING,
                    tagString:"singing"
                },
                tagEntry5Struct:{
                    tagTypeSubEnum:VERB_S,
                    tagString:"sings"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:VERB_INTRANSITIVE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:VERB_1,
                    tagString:"sleep"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:VERB_2,
                    tagString:"slept"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:VERB_3,
                    tagString:"slept"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:VERB_ING,
                    tagString:"sleeping"
                },
                tagEntry5Struct:{
                    tagTypeSubEnum:VERB_S,
                    tagString:"sleeps"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:VERB_INTRANSITIVE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:VERB_1,
                    tagString:"work"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:VERB_2,
                    tagString:"worked"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:VERB_3,
                    tagString:"worked"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:VERB_ING,
                    tagString:"working"
                },
                tagEntry5Struct:{
                    tagTypeSubEnum:VERB_S,
                    tagString:"works"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:VERB_INTRANSITIVE,
            }
        );
    }
    public static function TagGeneralStructVerbVoidTransitiveVoid(_collectionGlobalObject:CollectionGlobal){
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:VERB_1,
                    tagString:"assasinate"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:VERB_2,
                    tagString:"assasinated"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:VERB_3,
                    tagString:"assasinated"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:VERB_ING,
                    tagString:"assasinating"
                },
                tagEntry5Struct:{
                    tagTypeSubEnum:VERB_S,
                    tagString:"assasinates"
                },
                tagFeelEnum:NEGATIVE,
                tagTypeEnum:VERB_INTRANSITIVE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:VERB_1,
                    tagString:"buy"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:VERB_2,
                    tagString:"bought"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:VERB_3,
                    tagString:"bought"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:VERB_ING,
                    tagString:"buying"
                },
                tagEntry5Struct:{
                    tagTypeSubEnum:VERB_S,
                    tagString:"buys"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:VERB_TRANSITIVE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:VERB_1,
                    tagString:"call"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:VERB_2,
                    tagString:"called"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:VERB_3,
                    tagString:"called"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:VERB_ING,
                    tagString:"calling"
                },
                tagEntry5Struct:{
                    tagTypeSubEnum:VERB_S,
                    tagString:"calls"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:VERB_TRANSITIVE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:VERB_1,
                    tagString:"desire"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:VERB_2,
                    tagString:"desired"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:VERB_3,
                    tagString:"desired"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:VERB_ING,
                    tagString:"desiring"
                },
                tagEntry5Struct:{
                    tagTypeSubEnum:VERB_S,
                    tagString:"desires"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:VERB_TRANSITIVE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:VERB_1,
                    tagString:"drink"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:VERB_2,
                    tagString:"drunk"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:VERB_3,
                    tagString:"drank"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:VERB_ING,
                    tagString:"drinking"
                },
                tagEntry5Struct:{
                    tagTypeSubEnum:VERB_S,
                    tagString:"drinks"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:VERB_TRANSITIVE,
            }
        );

        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:VERB_1,
                    tagString:"drive"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:VERB_2,
                    tagString:"drove"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:VERB_3,
                    tagString:"driven"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:VERB_ING,
                    tagString:"driving"
                },
                tagEntry5Struct:{
                    tagTypeSubEnum:VERB_S,
                    tagString:"drives"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:VERB_TRANSITIVE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:VERB_1,
                    tagString:"eat"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:VERB_2,
                    tagString:"ate"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:VERB_3,
                    tagString:"eaten"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:VERB_ING,
                    tagString:"eating"
                },
                tagEntry5Struct:{
                    tagTypeSubEnum:VERB_S,
                    tagString:"eats"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:VERB_TRANSITIVE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:VERB_1,
                    tagString:"fight"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:VERB_2,
                    tagString:"fought"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:VERB_3,
                    tagString:"fought"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:VERB_ING,
                    tagString:"fighting"
                },
                tagEntry5Struct:{
                    tagTypeSubEnum:VERB_S,
                    tagString:"fights"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:VERB_TRANSITIVE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:VERB_1,
                    tagString:"get"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:VERB_2,
                    tagString:"got"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:VERB_3,
                    tagString:"gotten"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:VERB_ING,
                    tagString:"getting"
                },
                tagEntry5Struct:{
                    tagTypeSubEnum:VERB_S,
                    tagString:"gets"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:VERB_TRANSITIVE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:VERB_1,
                    tagString:"grab"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:VERB_2,
                    tagString:"grabbed"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:VERB_3,
                    tagString:"grabbed"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:VERB_ING,
                    tagString:"grabbing"
                },
                tagEntry5Struct:{
                    tagTypeSubEnum:VERB_S,
                    tagString:"grabs"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:VERB_TRANSITIVE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:VERB_1,
                    tagString:"kill"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:VERB_2,
                    tagString:"killed"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:VERB_3,
                    tagString:"killed"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:VERB_ING,
                    tagString:"killing"
                },
                tagEntry5Struct:{
                    tagTypeSubEnum:VERB_S,
                    tagString:"kills"
                },
                tagFeelEnum:NEGATIVE,
                tagTypeEnum:VERB_INTRANSITIVE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:VERB_1,
                    tagString:"love"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:VERB_2,
                    tagString:"loved"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:VERB_3,
                    tagString:"loved"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:VERB_ING,
                    tagString:"loving"
                },
                tagEntry5Struct:{
                    tagTypeSubEnum:VERB_S,
                    tagString:"loves"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:VERB_TRANSITIVE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:VERB_1,
                    tagString:"paint"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:VERB_2,
                    tagString:"painted"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:VERB_3,
                    tagString:"painted"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:VERB_ING,
                    tagString:"painting"
                },
                tagEntry5Struct:{
                    tagTypeSubEnum:VERB_S,
                    tagString:"paints"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:VERB_TRANSITIVE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:VERB_1,
                    tagString:"sell"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:VERB_2,
                    tagString:"sold"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:VERB_3,
                    tagString:"sold"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:VERB_ING,
                    tagString:"selling"
                },
                tagEntry5Struct:{
                    tagTypeSubEnum:VERB_S,
                    tagString:"sells"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:VERB_TRANSITIVE,
            }
        );
        _collectionGlobalObject.GetTagGeneralStructArray().push(
            {
                tagEntry1Struct:{
                    tagTypeSubEnum:VERB_1,
                    tagString:"shove"
                },
                tagEntry2Struct:{
                    tagTypeSubEnum:VERB_2,
                    tagString:"shoved"
                },
                tagEntry3Struct:{
                    tagTypeSubEnum:VERB_3,
                    tagString:"shoved"
                },
                tagEntry4Struct:{
                    tagTypeSubEnum:VERB_ING,
                    tagString:"shoving"
                },
                tagEntry5Struct:{
                    tagTypeSubEnum:VERB_S,
                    tagString:"shoves"
                },
                tagFeelEnum:NEUTRAL,
                tagTypeEnum:VERB_TRANSITIVE,
            }
        );
    }
}