enum EnumMuseumType{
    EXH;
    FLR;
    ROM;
}
enum EnumMuseumMode{
    REQ_CH_PARENT;
    MRK_DEL;
}
enum EnumTagFeelType{
    NEGATIVE;
    NEUTRAL;
    POSITIVE;
}
enum EnumTagType{
    ADJ;
    ADV;
    NOUN_ALIVE_ABSTRACT;
    NOUN_ALIVE_CONCRETE;
    NOUN_INANIMATE_HOLD_ABSTRACT;
    NOUN_INANIMATE_HOLD_CONCRETE;
    NOUN_INANIMATE_PLACE_ABSTRACT;
    NOUN_INANIMATE_PLACE_CONCRETE_NO_OWNER;
    NOUN_INANIMATE_PLACE_CONCRETE_OWNER;
    NOUN_INANIMATE_SEE_ABSTRACT;
    NOUN_INANIMATE_SEE_CONCRETE;
    NOUN_INANIMATE_TITLE;
    NOUN_INANIMATE_WEAR_ABSTRACT;
    NOUN_INANIMATE_WEAR_CONCRETE;
    VERB_INTRANSITIVE;
    VERB_TRANSITIVE;
}